<?php
/*
 * WARNING: This file is part of Photographers
 * DO NOT edit this file, under any circumstances.
 *
 * @package Photographers
 * @version 1
 * @php version 7.2.2
 * @laravel version 5.5
 * @author Zahid Hasan (http://zahidhasan.brotherhoodinfotech.com)
 * @copyright Copyright © 2017 - Zahid Hasan.
 * @last-modified 23/05/18
 */


namespace App\Http\Controllers\backend;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class DashboardControllerZA extends Controller
{
    public  function dashboarPhotographers($id){
        $userId = User::where('users_track_id', $id)->first();
        if (empty($userId)) {
            return redirect()->intended('pagenotfound');
        } else {
            $userId->users_veryfication_status="Active";
            Session::put('name',$userId->users_name);
            Session::put('users_track_id',$userId->users_track_id);
            $userId->save();
            return view('backend.photographersDashboard',compact('a'));
        }
    }
}
