<?php
/*
 * WARNING: This file is part of Photographers
 * DO NOT edit this file, under any circumstances.
 *
 * @package Photographers
 * @version 1
 * @php version 7.2.2
 * @laravel version 5.5
 * @author Zahid Hasan (http://zahidhasan.brotherhoodinfotech.com)
 * @copyright Copyright © 2017 - Zahid Hasan.
 * @last-modified 23/05/18
 */

namespace App\Http\Controllers\backend;
use App\Http\Controllers\Controller;

use App\TrackModelZA;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\URL;

class RegistrationControllerZA extends Controller
{
/*
 * Registration pnale
 * Functionlaity : resgistration page view
 */
    public function registerPhotographersView()
    {
        return view('backend.registrationPhotographers');
    }

    /*Registration Panel
     *Functionality :User Information Save into database and account veryfication message send users email address
     * if user veryfied his account user can accces dashboard
     */
    public function registrationPhotographers(Request $request)
    {
        $users_name = Input::get('users_name');
        $users_email = Input::get('users_email');
        $mobile_number = Input::get('mobile_number');
        $address = Input::get('address');

        $errors = array();
        /*
         * Checking user name is empty or not
         */
        if (empty($users_name) || $users_name == '') {
            $errors['users_name'] = "user name required";
        }
        /*
         * Checking user phone is empty or not
         */
        if (empty($users_email) || $users_email == '') {
            $errors['users_email'] = "user e-mail required";
        }

        if (empty($address) || $address == '') {
            $errors['address'] = "address is  required";
        }

        $number = ['011', '015', '016', '017', '018', '019'];
        $mobileNumber = str_split($mobile_number, 3);
        $mobileNumber[0];

        if (empty($mobile_number) || $mobile_number == '') {
            $errors['mobile_number'] = "mobile number required";
        }
        /*
         * Checking user phone number digit length 11 character or not
         */
        if (!empty($mobile_number)) {
            if (strlen($mobile_number) != 11) {
                $errors['mobile_number'] = "mobile number must be 11 digits";
            }
            /*
             * Checking phone number is numeric value or not
             */

            if (!is_numeric($mobile_number)) {
                $errors['mobile_number'] = "mobile number must be numeric value";
            }

            /*
             * Checking user moble number validation
             */

            if (!in_array($mobileNumber[0], $number)) {
                $errors['mobile_number'] = " phone number format does not match";
            }

        }

        /*
         * Checking email empty or not
         */
        if (!empty(Input::get('users_email'))) {
            if (!filter_var(Input::get('users_email'), FILTER_VALIDATE_EMAIL) === true) {
                $errors['users_email'] = " e-mail is not valid";
            } else {
                $checkExistsEmail = User::where('email', Input::get('users_email'))->exists();
                if ($checkExistsEmail) {
                    $errors['users_email'] = "user e-mail already exists";
                }
            }
        }

        if (count($errors) > 0) {
            return redirect()->back()->withInput()->withErrors($errors)->with('errorArray', 'Array Error Occured');
        } else {
                $randomNumber = new TrackModelZA();
                $trackId = $randomNumber->trackId(5, 10) . "ZA" . date("YmdHis");
                $obj = new User();
                $obj->users_track_id = $trackId;
                $obj->users_name = $users_name;
                $obj->email = $users_email;
                $obj->mobile_number = $mobile_number;
                $obj->address = $address;
                $obj->users_veryfication_status = 'Inactive';
                $obj->created_at = Carbon::now();

                if ($obj->save()) {
                    $checkExistsEmail = User::where('email', $users_email)->first();
                    if (!empty($checkExistsEmail)) {
                        $users_name = $checkExistsEmail->users_name;
                        $users_track_id = $checkExistsEmail->users_track_id;
                        if (!empty($users_track_id)) {
                            Mail::send('backend.confirmationMessage', array(
                                'link' => URL::to('portal/photogrphers/Dashboard/' . $users_track_id),
                                'users_name' => $users_name), function ($message) use ($users_name, $users_email) {
                                $message->from('infogotegary@gmail.com', 'Photographers');
                                $message->to($users_email, $users_name)->subject('Activate your account');
                                Log::info('End of mail processing');
                            });
                            return redirect('/')->with('success', 'Link send to you email and please veryfied your account through email');
                        }
                    } else {
                        return redirect()->back()->withInput()->with('error', 'Email not exists');
                    }

                }
        }

    }
}





